name: Deploy Full-Stack App to AlmaLinux

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22" # Recommended stable LTS version for most apps

      - name: Deploy to VPS
        env:
          DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          VPS_IP: ${{ secrets.VPS_IP }}
        run: |
          # Set up SSH
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

          # Deploy code and build the app
          ssh -i ~/.ssh/id_ed25519 vefrmeistari@${{ secrets.VPS_IP }} << 'EOF'
            set -e
            
            # Navigate to project directory
            cd /var/www/blogExcelSolutionsV
            
            # Pull latest code
            git pull origin main
            
            # Install backend dependencies
            npm install
            
            # Build frontend
            cd client
            npm install
            npm run build
            cd ..

            # Ensure PM2 restarts the app
            pm2 restart mern-blog || pm2 start server.js --name mern-blog
          EOF
